---
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/all"
  - "plugin:react-hooks/recommended"
parser: "@typescript-eslint/parser"
parserOptions:
  project: "./tsconfig.json"
plugins:
  - "@typescript-eslint"
rules:
  "@typescript-eslint/indent":
    - error
    - 2
  "@typescript-eslint/space-before-function-paren":
    - error
    - never
  # Allow functions to be Pascal case since we use React functional components
  "@typescript-eslint/naming-convention":
    - error
    - selector: "function"
      format: ["StrictPascalCase"]
ignorePatterns:
  - "**/*.test.tsx"
